Repository yalesites-org/yalesites-project, pull requests merged in 2022-07, with the labels that each got.

#59 YALB-495: Wire event paragraphs
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/crop.type.card_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1120.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1280.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1440.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1600.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1760.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1920.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2080.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2240.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_320.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_480.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_640.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_800.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_960.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1120.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1280.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1440.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1600.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1760.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_1920.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_2080.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_2240.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_2400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_320.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_480.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_640.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_800.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_960.yml
  web/profiles/custom/yalesites_profile/config/sync/image_widget_crop.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_featured_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
Labels: pass code review, pass functional review, ready to merge

#61 YALB-491: Wire news cards and views
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml
Labels: pass code review, pass functional review, ready to merge

#63 YALB-533: updates admin theme.
  web/themes/custom/ys_admin_theme/css/admin-ui.css
  web/themes/custom/ys_admin_theme/css/admin-ui.css.map
  web/themes/custom/ys_admin_theme/package-lock.json
  web/themes/custom/ys_admin_theme/scss/admin-ui.scss
  web/themes/custom/ys_admin_theme/ys_admin_theme.info.yml
  web/themes/custom/ys_admin_theme/ys_admin_theme.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#66 YALB-444: Remove github token step for setup
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#67 YALB-254: Allows pages to utility nav
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
Labels: needs review

#65 YALB-610: Wire Pager
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml
Labels: pass code review, pass functional review, ready to merge

#58 ci: enable Github Actions
  .ci/deploy/pantheon/dev-multidev
  .ci/test/static/run
  .github/workflows/build_deploy_and_test.yml
Labels: pass code review, ready to merge

#70 YALB-443: Add YS Core module with footer social links UI
  .npmrc
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/YSCoreFooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesSocialLinksBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-social-links.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
Labels: pass code review, pass functional review, ready to merge

#73 YALB-612: Refactor social links
  docs/development.md
  scripts/local/rebuild.sh
  scripts/local/setup.sh
  web/profiles/custom/yalesites_profile/config/sync/block.block.social_links_block.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/YSCoreFooterSettingsForm.php
Labels: pass code review, pass functional review, ready to merge
