Repository yalesites-org/yalesites-project, pull requests merged in 2022-09, with the labels that each got.

#94 Release
  .ci/deploy/pantheon/dev-multidev
  .circleci/config.yml
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_cards.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_cards.field_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_cards.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/override_node_options.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.custom_card.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.custom_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.quick_links.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: ready to merge

#71 YALB-637: DevOps: add support for building out the frontend
  .ci/build/build_frontend
  .github/workflows/build_deploy_and_test.yml
Labels: pass code review, pass functional review, ready to merge

#99 Release
  .ci/build/build_frontend
  .github/workflows/build_deploy_and_test.yml
  web/modules/custom/yale_cas/composer.json
  web/modules/custom/yale_cas/src/Routing/RouteSubscriber.php
  web/modules/custom/yale_cas/yale_cas.info.yml
  web/modules/custom/yale_cas/yale_cas.module
  web/modules/custom/yale_cas/yale_cas.services.yml
Labels: ready to merge

#97 YALB-607: Devops: fix site link comments not appearing in PRs
  .ci/deploy/pantheon/dev-multidev
Labels: pass code review, pass functional review, ready to merge

#96 YALB-599: Component overrides fields
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pull_quote.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text_with_image.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.pull_quote.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_width.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#100 YALB-684: Theme Settings: Generate CSS variables
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#101 YALB 502: Dynamic heading levels
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: needs review, pass functional review

#98 create theme script for development
  package.json
  scripts/local/dev-component-library-install.sh
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
Labels: needs review, review in progress

#105 YALB-719: Quick links style variation for link field
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass functional review

#103 YALB-681: News/Events: Base path setting and token
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.events.yml
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.news.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
Labels: pass code review, pass functional review, ready to merge

#102 Release
  .ci/deploy/pantheon/dev-multidev
  package.json
  scripts/local/dev-component-library-install.sh
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pull_quote.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text_with_image.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.pull_quote.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.events.yml
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.news.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: don't merge

#107 YALB-726: Make style variations per component required
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.pull_quote.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.text_with_image.field_style_width.yml
Labels: pass code review, pass functional review, ready to merge

#110 YALB-729: Bug: Creating accordion items
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#104 YALB-286: Add ability to get all theme settings in twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemesTwigExtension.php
Labels: pass code review, pass functional review, ready to merge

#111 YALB-699 Search Display
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.news.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
Labels: pass code review, pass functional review, ready to merge

#114 YALB-742: Update action banner
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/layout-paragraphs.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#113 YALB-712 create video paragraph
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.video.field_media_oembed_video.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.video.field_video.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_media_oembed_video.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_video.yml
  web/profiles/custom/yalesites_profile/config/sync/media.type.video.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.video.yml
Labels: pass code review, pass functional review, ready to merge

#125 YALB-295: Set accordion item cardinality
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_content.yml
Labels: pass code review, pass functional review, ready to merge

#119 YALB-281: Document: Create media type
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_media_file.yml
  web/profiles/custom/yalesites_profile/config/sync/media.type.document.yml
Labels: pass code review, pass functional review, ready to merge

#115 YALB-700: Search Form and Settings
  web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_actions.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_local_tasks.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_messages.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.exposedformsearchpage_1.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.main_page_content.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.pagetitle.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.yalesitesbreadcrumbs.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/config/sync/search_api.server.database_server.yml
  web/profiles/custom/yalesites_profile/config/sync/views.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#121 YALB-703: Search: Opt out of index
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.event.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
Labels: pass code review, pass functional review, ready to merge

#124 YALB-736: Feedback: Remove starterkit install hooks
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/ys_starterkit.install
Labels: pass code review, ready to merge

#118 YALB-732: Pages: Url Alias defaults
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.page.yml
Labels: pass code review, pass functional review, ready to merge

#126 YALB-717: Bug: Breadcrumbs for content without a menu link
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
Labels: pass code review, pass functional review, ready to merge

#127 YALB-271: hides media form fields
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: pass code review, pass functional review, ready to merge

#128 YALB-518: AX: Ability to clone nodes
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/quick_node_clone.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge
