Repository yalesites-org/yalesites-project, pull requests merged in 2022-08, with the labels that each got.

#76 YALB-438: creates tabs paragraph
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tabs.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.tab.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.tabs.default.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.heading_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tab.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tab.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tabs.field_tab.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_tab.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.tab.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.tabs.yml
Labels: pass code review, pass functional review, ready to merge

#77 YALB-661: Fix duplicate accordion controls
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_paragraph_accordion.yml
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_paragraph_accordion_item.yml
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_paragraph_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_paragraphs.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_paragraph_accordion.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_paragraph_accordion_item.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_paragraph_callout.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_paragraphs.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraph_accordion_item.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
Labels: pass code review, pass functional review, ready to merge

#78 YALB-635: Add is_active to breadcrumb items to denote active page
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-breadcrumb-block.html.twig
Labels: pass code review, pass functional review, ready to merge

#82 YALB-667 - Prepend home to breadcrumb list
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
Labels: needs review

#81 feat(YALB-328): Ignore site specific config settings
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.social_links.yml
Labels: pass code review, pass functional review, ready to merge

#84 YALB-286: Theme settings twig function
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/Form/YSThemesSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/Service/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/YSThemesTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.services.yml
Labels: pass code review, pass functional review, ready to merge

#83 YALB-100: Theme Service and Settings Interface
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.site_specific_ignored_config.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.social_links.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/Form/YSThemesSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/Service/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.services.yml
Labels: pass functional review

#80 YALB-288: Demo Content Updates
  web/profiles/custom/yalesites_profile/config/sync/system.site.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_alert.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraph_callout.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
Labels: pass code review, pass functional review, ready to merge

#85 YALB-91: Custom cards create paragraph
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_cards.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_cards.field_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_cards.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.custom_card.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.custom_cards.yml
Labels: pass code review, pass functional review, ready to merge

#87 YALB-105: Quick links paragraph
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.quick_links.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.quick_links.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.paragraph.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.quick_links.yml
Labels: pass code review, pass functional review, ready to merge

#88 YALB-41: Promoted news/events items
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.news_list.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#90 YALB-590: News: Change publication date
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/override_node_options.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#93 YALB-691: Update machine color names to match component library
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review, ready to merge

#92 YALB-685: DevOps: remove CirceCI configuration
  .circleci/config.yml
Labels: pass code review, ready to merge

#91 YALB-687: DevOps: fix intermittent failed CI builds
  .ci/deploy/pantheon/dev-multidev
Labels: pass code review, ready to merge
