Repository yalesites-org/yalesites-project, pull requests merged in 2022-10, with the labels that each got.

#129 YALB-702: Fix error message for show/hide search config
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#122 YALB-282: AX: Add button to edit media
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.media_grid_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pop_out_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/themes/custom/ys_admin_theme/css/admin-ui.css
  web/themes/custom/ys_admin_theme/css/admin-ui.css.map
  web/themes/custom/ys_admin_theme/scss/admin-ui.scss
Labels: work in progress

#130 YALB-766: action banner button
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_banner.field_link.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
Labels: pass code review, pass functional review, ready to merge

#134 YALB-752: set max lengths in drupal
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.news.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.embed.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.event_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.media_grid.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.news_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.video.default.yml
Labels: pass code review, pass functional review, ready to merge

#132 YALB-297: AX: Add linkit field module
  composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.embed.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.text_with_image.default.yml
Labels: pass code review, pass functional review, ready to merge

#123 YALB-762: Bug: Fix CI build - multidev not created
  .ci/build/build_frontend
  .ci/deploy/pantheon/dev-multidev
  .github/workflows/build_deploy_and_test.yml
  .gitignore
Labels: pass code review, pass functional review, ready to merge

#135 YALB-283: AX: Remove confusing remove-button
  composer.json
Labels: pass code review, pass functional review, ready to merge

#131 YALB-683: News/Events: Breadcrumbs
  web/profiles/custom/yalesites_profile/config/sync/menu_breadcrumb.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/pathauto.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/YaleSitesBreadcrumbsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
Labels: pass code review, pass functional review, ready to merge

#106 YALB-636: DevOps: fix tests in the Github Actions workflow
  .ci/test/static/lint_php
  .ci/test/static/run
  .github/workflows/build_deploy_and_test.yml
  composer.json
  package.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/SocialLinksManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/src/Config/MailConfigOverrides.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemesTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/profiles/custom/yalesites_profile/yalesites_profile.profile
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
Labels: pass code review, pass functional review, ready to merge

#139 YALB-628: disables preview for content types
  web/profiles/custom/yalesites_profile/config/sync/node.type.event.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.news.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.page.yml
Labels: pass code review, pass functional review, ready to merge

#145 YALB-793: CI: check for module additions to root composer.json
  .github/workflows/build_deploy_and_test.yml
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#143 YALB-768: local development scripts
  .ci/test/static/run
  .gitignore
  composer.json
  package.json
  reference/.gitkeep
  scripts/local/assets-pull.sh
  scripts/local/build-theme.sh
  scripts/local/build-with-assets.sh
  scripts/local/build.sh
  scripts/local/confim.sh
  scripts/local/db-create.sh
  scripts/local/db-get.sh
  scripts/local/db-import.sh
  scripts/local/db-local-export.sh
  scripts/local/files-get.sh
  scripts/local/get-assets.sh
  scripts/local/get-db.sh
  scripts/local/lint.sh
  scripts/local/local-cl-update.sh
  scripts/local/local-review-with-atomic-branch.sh
  scripts/local/local-review-with-cl-branch.sh
  scripts/local/rebuild.sh
  scripts/local/setup.sh
  scripts/local/theme.sh
Labels: needs review, pass code review, pass functional review

#147 YALB-768: Local Dev Scripts
  README.md
  docs/development.md
  docs/theming.md
  package.json
  scripts/local/assets-pull.sh
  scripts/local/build-with-assets.sh
  scripts/local/build.sh
  scripts/local/local-cl-dev.sh
  scripts/local/local-cl-update.sh
  scripts/local/local-review-with-atomic-and-cl-branch.sh
  scripts/local/local-review-with-atomic-branch.sh
  scripts/local/local-review-with-cl-branch.sh
Labels: pass code review, pass functional review, ready to merge

#144 YALB-756: Rename pop out image to wrapped image
  README.md
  package.json
  scripts/local/build-with-install.sh
  scripts/local/local-review-with-atomic-branch.sh
  scripts/local/local-review-with-cl-branch.sh
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.wrapped_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.wrapped_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.wrapped_image.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.news.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_cards.field_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.gallery.field_gallery_items.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.media_grid.field_media_grid_items.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tab.field_content.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.tabs.field_tab.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.wrapped_image.field_caption.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.wrapped_image.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.wrapped_image.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.wrapped_image.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/paragraphs.json
Labels: needs review, pass functional review

#150 feat (YALB-291): create resource block and organize dashboard
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesDashboardResourcesBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-dashboard-resources.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/themes/custom/ys_admin_theme/templates/ys/ys-dashboard-resources.html.twig
  web/themes/custom/ys_admin_theme/templates/ys/ys-dashboard.html.twig
Labels: pass code review, pass functional review, ready to merge
