Repository yalesites-org/yalesites-project, pull requests merged in 2022-05, with the labels that each got.

#23 fix: increase process-timeout for composer
  composer.json
Labels: pass code review, pass functional review, ready to merge

#22 YALB-525: Two Column Layout Builder Layout
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/layouts/two-column/ys-layouts--yds-twocol.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.layouts.yml
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
Labels: pass code review, pass functional review, ready to merge

#20 YALB-476: Wire Image Paragraph
  scripts/local/rebuild.sh
  scripts/local/setup.sh
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_content.yml
Labels: needs review, pass code review, pass a11y review

#25 refactor: move composer timeout to landofile from composer.json
  .lando.local.example.yml
  composer.json
Labels: pass code review, pass functional review, ready to merge

#30 YALB-519 - adds Editoria11y module
  composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editoria11y.settings.yml
Labels: pass code review, pass functional review, ready to merge

#28 YALB-473: Disable integrated composer
  .ci/build/php
  .ci/build/set-composer-source
  .ci/build/theme
  .ci/deploy/multidev
  .circleci/config.yml
  composer.json
  pantheon.upstream.yml
  scripts/composer/ScriptHandler.php
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#29 YALB-527: Image Cropping
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_16_5.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_banner.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.image.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.pop_out_image.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.text.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.banner_16_5.yml
  web/profiles/custom/yalesites_profile/config/sync/crop.type.banner_16_5.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1120.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1280.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1440.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1600.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1760.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_1920.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2080.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2240.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_2400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_320.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_480.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_640.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_800.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_5_960.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.banner_16_5_.yml
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#33 YALB-451: BE: Roles and Permissions
  web/profiles/custom/yalesites_profile/config/sync/system.action.user_add_role_action.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/system.action.user_add_role_action.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/system.action.user_remove_role_action.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/system.action.user_remove_role_action.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge

#34 YALB-440: SSO Setup
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/cas_attributes.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.user.user.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.user.user.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.user.user.field_first_name.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.user.user.field_last_name.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.user.field_first_name.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.user.field_last_name.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.user_admin_people.yml
Labels: pass code review, pass functional review, ready to merge

#21 YALB-377: Adds linting
  .ci/.npmrc-example
  .ci/test/static/run
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  build-providers.json
  commitlint.config.js
  composer.json
  docs/CONTRIBUTING.md
  docs/setup.md
  docs/upstream.md
  package.json
  prettierrc.js
  scripts/local/lint.sh
  scripts/local/test.sh
  stylelint.config.js
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/src/Config/MailConfigOverrides.php
Labels: pass code review, pass functional review, ready to merge

#41 YALB-558: CI Fixes
  .circleci/config.yml
  pantheon.upstream.yml
Labels: pass code review, pass functional review, ready to merge

#42 ci(YALB-558): reset ci
  .ci/build/php
  .ci/deploy/pantheon/dev-multidev
  .circleci/config.yml
  composer.json
Labels: pass code review, pass functional review, ready to merge

#44 YALB-536: configs layout_paragraphs modal
  web/profiles/custom/yalesites_profile/config/sync/layout_paragraphs.modal_settings.yml
Labels: pass code review, pass functional review, ready to merge
