Repository yalesites-org/yalesites-project, pull requests merged in 2023-09, with the labels that each got.

#408 YALB-1510: Mega Menu: Present Level One links as Headings - BE
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/captcha.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.menu_link_content.main.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.menu_link_content.main.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.menu_link_content.main.field_menu_top_level_link_cta.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.menu_link_content.field_menu_top_level_link_cta.yml
  web/profiles/custom/yalesites_profile/config/sync/menu_item_extras.utility.yml
  web/profiles/custom/yalesites_profile/config/sync/node.type.profile.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review, pass code review, pass functional review

#410 YALB-1552: [admin-theme] Update specific checkbox styles for admin-theme areas
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/css/ys_alert.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: pass code review, pass functional review

#407 YALB-1416: Bug: Empty Headings in HTML | YALB-1312: Bug: Style views Event Time Period radio buttons | YALB-1215: Dials: Banner heading levels
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_heading_level.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_heading_level.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_heading_level.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/event-time-all.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/event-time-future.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/event-time-past.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: needs review, pass code review, pass functional review

#414 HOTFIX: Fix Nodes not able to be viewed if no menu item
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#411 YALB-1291: Update to CKEditor5
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.heading_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.webform_default.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.webform_default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/layout-builder-fix-modals.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
Labels: needs review, question

#406 YALB-1485/YALB-1486/YALB-1488: Mega Footer
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/block.block.yalesitesfooterblock.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_180.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_220.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_250.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_content_width.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_logos.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.footer_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/footer-settings-form.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/icons/disabled-details.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/footer-basic.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/footer-mega.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/footer-settings.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-footer-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review

#418 YALB-1462: Bug: Content Spotlight Requires Link
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_link.yml
Labels: pass code review, pass functional review, ready to merge

#424 Event Sections
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/UpdateExistingNodes.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.deploy.php
Labels: pass code review, pass functional review

#392 YALB-1057: Add automatic smartquotes
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
Labels: pass code review, pass functional review, ready to merge

#426 YALB-1554: Remove "Platform admin" from options for site admins when adding or managing site users
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#421 YALB-1303: Finding content tagged with a specific tag
  web/profiles/custom/yalesites_profile/config/sync/chosen.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
  web/themes/custom/ys_admin_theme/css/gin-custom.css
Labels: needs review, pass code review, pass functional review

#419 Yalb mega footer 2
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/crop.type.logo_horizontal_3_1.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.1_1_250.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_1_300.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_1_400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_1_500.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_1_600.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_1_700.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_horizontal_logos.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_logos.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/footer-settings-form.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-footer-block.html.twig
Labels: needs review

#432 YALB-1373: Feedback: URLs with filler words
  web/profiles/custom/yalesites_profile/config/sync/pathauto.settings.yml
Labels: pass code review, pass functional review, ready to merge

#425 YALB-1423 - Feedback: Rename floated to inline | YALB-1425 - Bug: Firefox - GIF being uploaded to multiple blocks | YALB-1426 - Bug: Exposed taxonomy filter style on mobile
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.image.field_media_image.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: pass code review, pass functional review, ready to merge

#433 fix(YALB-email-copy-change-to-button): update component to use for em…
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-profile-contact-block.html.twig
Labels: pass code review, pass functional review, ready to merge

#435 YALB-1385: Feedback: Yale Logo with submenus
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
Labels: pass code review, pass functional review, ready to merge

#439 YALB-1566: Fix deployment for Berkeley Divinity
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/UpdateExistingNodes.php
Labels: pass code review
