Repository yalesites-org/yalesites-project, pull requests merged in 2023-11, with the labels that each got.

#473 fix(permissions): add block content permissions
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: needs review

#464 YALB-961: WYSIWYG: Text field size to reflect character limits
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.wrapped_image.default.yml
Labels: pass code review, pass functional review, ready to merge

#474 YALB-1387: WYSIWYG: Clarity on maxlength
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.accordion.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.directory.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.event_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.gallery.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.media_grid.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.post_list.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.pull_quote.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.webform.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.accordion_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.tab.default.yml
Labels: pass code review, pass functional review

#484 Add conditional logic to `drush deploy` quicksilver script
  pantheon.yml
  web/private/scripts/confim.php
  web/private/scripts/drush_deploy.php
Labels: pass code review, ready to merge

#485 feat(YALB-656): enable email matcher in default linkit profile
  web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
Labels: pass code review, pass functional review, ready to merge

#483 YALB-1578 - Bug: FE: Search results pagination | YALB-1625 - Bug: FE: Profile search result wrong formatting
  web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
Labels: pass code review, pass functional review, ready to merge

#486 YALB-1537 AX: Remove Items from multivalue fields
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: pass code review, pass functional review, ready to merge

#488 YALB-1584: Update dashboard content
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesDashboardResourcesBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesSupportFormBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-dashboard-resources.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-dashboard.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-social-links.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-support-form.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/themes/custom/ys_admin_theme/templates/ys/ys-dashboard-resources.html.twig
  web/themes/custom/ys_admin_theme/templates/ys/ys-dashboard.html.twig
Labels: needs review

#469 YALB-1574: Branding: Header Variations Backend
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.background_image_16_9_focus_header.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.media.background_image_16_9_focus_header.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_1000.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_1400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_1800.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_2400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_400.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_600.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.16_9_800.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.background_image_focus_header.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/header-footer-settings.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/header-basic.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/header-focus.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/header-mega.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/lever-nav-center.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/lever-nav-left.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/lever-nav-right.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/header-footer-settings.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/YaleSitesMediaManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.install
  web/themes/custom/ys_admin_theme/templates/content-edit/file-managed-file--svg.html.twig
  web/themes/custom/ys_admin_theme/templates/content-edit/image-widget.html.twig
Labels: pass code review, pass functional review

#491 YALB-1574: Branding: Header Variation Backend Front Page Alias Fix
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#487 YALB-1573: Allow admins to manage affiliation terms
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
Labels: pass code review, pass functional review, ready to merge

#494 YALB-1648: Bug: empty footer logo instance causes PHP fatal error
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
Labels: pass code review, pass functional review

#496 YALB-1602: Bug: Clone nodes with accordions and callouts wont allow user to edit
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge
