Repository yalesites-org/yalesites-project, pull requests merged in 2023-03, with the labels that each got.

#226 YALB-1011: View Pagination
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/ViewsBasicFilter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-rows.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: pass code review, pass functional review, ready to merge

#231 YALB-1044: Feedback: Error installing Linkit Patch
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#229 YALB-1006: Create views builder widget
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.basic_view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_vb_params.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/node-edit-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig
Labels: pass code review, pass functional review, ready to merge

#228 fix(yalb-951): fix widths on text-with-image override
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/layouts/two-column/ys-layouts--two-column.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: pass code review, pass functional review, ready to merge

#232 Release
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.basic_view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.basic_view.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.basic_view.field_vb_params.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/node-edit-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/layouts/two-column/ys-layouts--two-column.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/ViewsBasicFilter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-preview.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-rows.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
  web/themes/custom/ys_admin_theme/css/admin-ui.css
  web/themes/custom/ys_admin_theme/css/admin-ui.css.map
  web/themes/custom/ys_admin_theme/scss/admin-ui.scss
Labels: pass code review, pass functional review, ready to merge

#233 YALB-1016: DevOps: Post Deploy Commands
  pantheon.yml
  web/private/scripts/confim.php
Labels: pass code review, ready to merge

#234 Layout builder blocks
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.embed.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.image.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.video.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.webform.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.embed.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.webform.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.embed.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.webform.default.yml
  web/profiles/custom/yalesites_profile/config/sync/editoria11y.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.embed.field_instructions.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.embed.field_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image.field_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image.field_instructions.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_instructions.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.webform.field_form.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.webform.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.webform.field_instructions.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_form.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_media.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.action_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.embed.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.gallery.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.video.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.webform.yml
Labels: question
