Repository yalesites-org/yalesites-project, pull requests merged in 2023-06, with the labels that each got.

#289 YALB-818 - Views: Add icons as controls
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/content-type-event.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/content-type-page.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/content-type-post.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/content-type-profile.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/display-type-card-grid.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/icons/display-type-list-view.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#295 YALB-1239: Filter to show past events
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/EventTimePeriod.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: needs review, pass code review, pass functional review, ready to merge

#298 YALB-1294: Install and configure Bugherd module for testing
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/bugherd.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.anonymous.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml
Labels: pass code review, pass functional review

#296 YALB-1246: Bug: Linkit widget broken
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
Labels: pass code review, pass functional review, ready to merge

#300 YALB-1212: Enable taxonomy interfaces for authors
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.event_category.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.post_category.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.tags.default.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_category.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_type.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.post_category.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.tags.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/taxonomy-form.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review

#307 YALB-1248: Bug: Tablesort icons missing
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesSupportFormBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldFormatter/EmbedDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldWidget/EmbedDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/media/Source/Embed.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/src/EventSubscriber/NodeAccessEventSubscriber.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/src/SecretsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldType/ViewsBasicParams.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review

#303 YALB-608, YALB-731, YALB-1225, YALB-1236: Performance Local vs Production
  scripts/local/setup.sh
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/local_config/.htaccess
  web/profiles/custom/yalesites_profile/config/local_config/devel.settings.yml
  web/profiles/custom/yalesites_profile/config/local_config/devel.toolbar.settings.yml
  web/profiles/custom/yalesites_profile/config/local_config/system.menu.devel.yml
  web/profiles/custom/yalesites_profile/config/production_config/.htaccess
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.local_config.yml
  web/profiles/custom/yalesites_profile/config/sync/config_split.config_split.production_config.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/pantheon_advanced_page_cache.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/system.performance.yml
  web/sites/default/services.yml
  web/sites/default/settings.php
  web/sites/theming.services.yml
  web/sites/ys.settings.local.php
Labels: needs review

#304 YALB-1241: Deploy Siteimprove analytics JavaScript
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review

#308 YALB-1235: Media: Configure image toolkit/settings
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/file_mdm.file_metadata_plugin.getimagesize.yml
  web/profiles/custom/yalesites_profile/config/sync/file_mdm.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/imagemagick.file_metadata_plugin.imagemagick_identify.yml
  web/profiles/custom/yalesites_profile/config/sync/imagemagick.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/sophron.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/system.image.yml
Labels: needs review

#302 YALB-1300: Bug: Error when creating a new event
  README.md
  patches/add-php-c-format.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.layout_builder__layout.yml
Labels: pass code review, pass functional review, ready to merge

#310 YALB-1022: Bug: Grand Hero Design Option labels flipped
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.install
Labels: pass code review, pass functional review, ready to merge

#312 Remove media library upload button patch for Gin LB
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#321 YALB-1333: Source correct location of say.sh
  scripts/local/local-review-with-atomic-branch.sh
  scripts/local/local-review-with-cl-branch.sh
Labels: pass code review, pass functional review

#318 YALB-1313: Bug: Menu levers not updating website (BE)
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#320 YALB-1288: Bug: Search no results message (BE)
  web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
Labels: pass code review, pass functional review, ready to merge

#317 YALB-1293: updates default settings to use basic navigation inst…
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
Labels: pass code review, pass functional review, ready to merge

#323 YALB-1304, YALB-1344: Alert Settings Bugs
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
Labels: pass code review, pass functional review, ready to merge

#324 fix(YALB-1189): Site admins should not be able to configure site-wide…
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge

#329 YALB-1136: Move bugherd button to the left
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.pull_quote.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.text.yml
  web/profiles/custom/yalesites_profile/config/sync/bugherd.settings.yml
Labels: pass code review, pass functional review, ready to merge

#327 YALB-1318: Bug: media library - gallery block - multiple photos error
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#294 YALB-1257: Bug: Admin menu link color | YALB-1263 - Layout Builder spacing between components
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
Labels: needs review

#331 YALB-1363 - Bug: Media Grid images are different sizes on the main page
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.media_grid_item.default.yml
Labels: needs review

#332 YALB-1295: Bug: Posts display date of creation and not Publish Date
  web/profiles/custom/yalesites_profile/config/sync/pathauto.pattern.post.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.post_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.post_list.yml
Labels: pass code review, pass functional review, ready to merge
