Repository yalesites-org/yalesites-project, pull requests merged in 2023-08, with the labels that each got.

#368 Views basic fixes
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#374 Hotfix: ChosenJS Composer Install Fix
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#379 YALB-1495: Branding: Customized favicon
  web/favicons/android-chrome-192x192.png
  web/favicons/browserconfig.xml
  web/favicons/mstile-150x150.png
  web/favicons/safari-pinned-tab.svg
  web/favicons/site.webmanifest
  web/profiles/custom/yalesites_profile/config/sync/captcha.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.favicon_16x16.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.favicon_16x16_ico.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.favicon_180x180.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.favicon_32x32.yml
  web/profiles/custom/yalesites_profile/config/sync/imagemagick.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/favicons/apple-touch-icon.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/favicons/favicon-16x16.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/favicons/favicon-32x32.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/favicons/favicon.ico
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/FaviconManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/themes/custom/ys_admin_theme/css/favicon-preview.css
  web/themes/custom/ys_admin_theme/templates/content-edit/file-managed-file--favicon.html.twig
  web/themes/custom/ys_admin_theme/templates/content-edit/image-widget.html.twig
  web/themes/custom/ys_admin_theme/ys_admin_theme.libraries.yml
Labels: pass code review, pass functional review

#389 YALB-1518: View missing on resource library
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: needs review

#384 Update develop from master
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#394 YALB-1538: Bug: Node redirects do not work
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#399 YALB-1495: Fix image uploading and editing
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review, review in progress

#397 YALB-1382: Bug: NetID Required on node does not restrict page
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.install
Labels: pass code review, pass functional review, ready to merge

#400 YALB-1382: Bug: NetID Required on node does not restrict page fix
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.info.yml
Labels: pass code review, pass functional review

#401 YALB-1539: Bug: Taxonomy terms do not update in post feed or calendar list visually until user hits "Apply"
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review

#403 YALB-1446: Feedback: Views UI Matching Labels
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: pass code review, pass functional review

#398 CI: remove tmate debug
  .github/workflows/build_deploy_and_test.yml
Labels: pass code review, ready to merge

#396 YALB-1242: Use Pantheon Secrets
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/key.config_override.mailchimp_transactional_api_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v2_secret_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v2_site_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v3_secret_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.config_override.recaptcha_v3_site_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.key.mailchimp_transactional_api_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v2_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v2_secret.yml
  web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v3_key.yml
  web/profiles/custom/yalesites_profile/config/sync/key.key.recaptcha_v3_secret.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/ys_captcha.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/ys_captcha.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.module
  web/sites/default/settings.php
Labels: pass code review, pass functional review, ready to merge

#388 YALB-1501: Bug: Missing admin styles - Alternate Admin Theme Approach
  web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/css/ys_alert.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css.map
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review, pass code review, pass functional review
