Repository yalesites-org/yalesites-project, pull requests merged in 2023-04, with the labels that each got.

#235 fix(yalb-alignment): increase wrapped image width
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.image_float.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
Labels: pass code review, pass functional review, ready to merge

#239 YALB-1096: Use Simple Sitemap instead of XML Sitemap
  .ci/build/build_frontend
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.bundle_settings.default.menu_link_content.main.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.bundle_settings.default.node.event.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.bundle_settings.default.node.news.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.bundle_settings.default.node.page.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.bundle_settings.menu-links-only.menu_link_content.main.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.custom_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.custom_links.menu-links-only.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.sitemap.default.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.sitemap.index.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.sitemap.menu-links-only.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.type.default_hreflang.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.type.index.yml
  web/profiles/custom/yalesites_profile/config/sync/simple_sitemap.type.menu_links_sitemap.yml
  web/profiles/custom/yalesites_profile/config/sync/xmlsitemap.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/xmlsitemap.xmlsitemap.NXhscRe0440PFpI5dSznEVgmauL25KojD7u4e9aZwOM.yml
Labels: pass code review, pass functional review, ready to merge

#242 YALB-1083: Content Model: Restrict blocks by role
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: pass code review, pass functional review, ready to merge

#243 YALB-1043: Nav: Allow authors to use manage menu UI
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
Labels: needs review, pass code review, pass functional review, ready to merge

#248 (hotfix) YALB-1140: File upload field is missing
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
Labels: pass code review, pass functional review, ready to merge

#246 YALB-984: Wire new global themes
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, ready to merge

#249 YALB-1113: Enable modal layout browser
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
Labels: pass code review, pass functional review, ready to merge
