Repository yalesites-org/yalesites-project, pull requests merged in 2023-10, with the labels that each got.

#438 YALB-1527 - Bug: Update link styling "Skip to Main Content" | YALB-1560 - Blank space in toolbar on admin theme
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: pass code review, pass functional review

#445 fix(YALB-1569): Fix search indexing prevented by PostMetaBlock issue
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php
Labels: needs review, pass code review, pass functional review

#446 YALB-1564: Header: Mega Menu Description Link
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review, pass code review, pass functional review

#447 Hotfix for Search API on live sites
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/UpdateExistingNodes.php
Labels: needs review

#441 YALB-1562 - Color: Update tokens for existing color palettes - remove global themes 4 and 5 - add header accent, footer accent
  docs/color-theme.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-footer-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review

#431 YALB-1443: Bug: Disable links in quicklink content field
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_text.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
Labels: pass code review, pass functional review, ready to merge

#458 YALB-863: Set default value callbacks for all block dials
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_image.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_image.field_style_variation.yml
Labels: pass code review, pass functional review, ready to merge

#453 YALB-1577: Fix time format on condensed events
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.condensed.yml
Labels: pass code review, pass functional review, ready to merge

#452 YALB-1579: Fixing theme form error messages
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#456 YALB-1204: Update all custom module readme files
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/README.md
Labels: ready to merge

#457 YALB-1155: Add data model best practices do developer Readme file
  docs/development.md
Labels: ready to merge

#422 Fixes for semantic release
  .github/workflows/release.yml
  package.json
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
Labels: pass code review, ready to merge

#423 YALB-1472: Bug: Image generation failures
  scripts/local/images/calculateMB.sh
  scripts/local/images/doItAll.sh
  scripts/local/images/fix_images.sh
  scripts/local/images/get_images.sh
  scripts/local/images/put_images.sh
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.image.field_media_image.yml
  web/profiles/custom/yalesites_profile/config/sync/imagemagick.settings.yml
Labels: pass code review, pass functional review, ready to merge

#462 YALB-1593: Bug: FE: Views pagination not showing on front end
  patches/add-php-c-format.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: pass code review, pass functional review, ready to merge
