Repository yalesites-org/yalesites-project, pull requests merged in 2023-07, with the labels that each got.

#330 YALB-1411/1412/1329: Update toolbar labels, add unpublish button
  web/profiles/custom/yalesites_profile/config/sync/block.block.ys_admin_theme_local_tasks.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/ys_toolbar.module
Labels: pass code review, pass functional review, ready to merge

#343 YALB-1448: Bug - Media library wont allow item selections
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review

#342 YALB-1450: Link field truncates and breaks long links
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.button_link.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.custom_card.default.yml
Labels: pass code review, pass functional review

#341 YALB-597: Enable linkit for homepage setting
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
Labels: pass code review, pass functional review

#337 YALB-1256: Consistant 'add' label for reference fields
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.custom_cards.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.gallery.default.yml
Labels: pass code review, pass functional review

#336 YALB-1434: Increate max video size
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_media_video_file.yml
Labels: pass code review, pass functional review

#335 YALB-1290: Bug: Grand Hero Text alignment
  web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
Labels: needs review

#340 YALB-309: Metadata: Teaser instruction and help text (UX/SB)
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_teaser_title.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_teaser_title.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_title.yml
Labels: pass code review, pass functional review, ready to merge

#347 YALB-1208: Link to documents in WYSIWYG links
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
Labels: needs review

#345 YALB-1419 - OPAC: Move admin toolbar to top
  web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml
Labels: pass code review, pass functional review

#351 YALB-1297: Media: Verify images are using optimized styles
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_175.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.3_2_540.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_444.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.max_width_540.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.banner_16_5_.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_featured_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/responsive_image.styles.text_with_image_feature_equal.yml
Labels: pass code review, pass functional review, ready to merge

#352 YALB-898: Metadata: Add favicon
  web/favicons/android-chrome-192x192.png
  web/favicons/apple-touch-icon.png
  web/favicons/browserconfig.xml
  web/favicons/favicon-16x16.png
  web/favicons/favicon-32x32.png
  web/favicons/favicon.ico
  web/favicons/mstile-150x150.png
  web/favicons/safari-pinned-tab.svg
  web/favicons/site.webmanifest
  web/profiles/custom/yalesites_profile/config/sync/system.theme.global.yml
Labels: pass code review, pass functional review

#355 YALB-1452: Bug: StarterKit Migrations failed: Update Drush
  composer.json
Labels: pass code review, pass functional review, ready to merge

#364 YALB-1465: Switch CI scripts to use drush `deploy`
  .ci/deploy/pantheon/dev-multidev
Labels: pass code review, pass functional review

#358 YALB-1164 - OPAC: Update admin toolbar icons | 1461 - OPAC: Implement new admin colors and fonts
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/images/edit_layout_content.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/images/manage_settings.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/images/more_actions.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/images/publish.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/images/unpublish.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css.map
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review

#365 YALB-1388 - Feedback: Embed Block | YALB-1390 - Remove transparency from banner overlay | YALB-1417 - Bug: Block picker in Posts and Events only have 2 columns compared to 3 on Pages | YALB-1463 - Bug: Content Spotlight Border severely impacts use/placement of Block | YALB-858 - Feedback: Site Name looks too small on mobile
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#359 Bug: CAS user email addresses not being updated on login
  web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/cas_attributes.settings.yml
Labels: pass code review, pass functional review, ready to merge
