Repository yalesites-org/yalesites-project, pull requests merged in 2023-05, with the labels that each got.

#253 YALB-1091 - Style admin forms that appear in atomic
  web/profiles/custom/yalesites_profile/config/sync/views.view.frontpage.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.layouts.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#251 YALB-261: Local Dev Setup Xdebug
  .lando.local.example.yml
  docs/xdebug.md
Labels: needs review

#256 YALB-1137: Dividers add new dials to divider block
  scripts/local/local-review-with-cl-branch.sh
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.divider.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.divider.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.divider.field_style_width.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: needs review, pass code review, pass functional review, ready to merge

#260 YALB-855: Close modal after adding block
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#259 YALB-1183: Update labels on toolbar
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
Labels: pass code review, pass functional review, ready to merge

#261 Hide revision field patch cleanup
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#262 fix(YALB-1123): Cache invalidated on alert save
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.module
Labels: pass code review, pass functional review

#264 YALB-457: sets max-length for teaser text fields
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
Labels: pass code review, pass functional review, ready to merge

#265 YALB-814: Metatags Open Graph (SB/BE)
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.token.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.global.yml
  web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.node.yml
  web/profiles/custom/yalesites_profile/config/sync/metatag.metatag_defaults.node__post.yml
  web/profiles/custom/yalesites_profile/config/sync/metatag.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.tokens.inc
Labels: pass code review, pass functional review, ready to merge

#263 YALB-395: Metadata: Fallback for teaser images (BE)
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
Labels: pass code review, pass functional review, ready to merge

#254 YALB-988: Override Gin colors and typography
  web/profiles/custom/yalesites_profile/config/sync/gin.settings.yml
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css.map
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/css/gin-overrides.css.map
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
  web/themes/custom/ys_admin_theme/ys_admin_theme.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#272 YALB-1190: Fixes alert setting select bug
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/css/ys_alert.css
Labels: pass code review, pass functional review, ready to merge

#271 YALB-1205: Webform buttons: add preprocess to pass data-cta-theme attribute
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: needs review, pass functional review

#274 YALB-892: Media: Update Character Limits (SB)
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.wrapped_image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.gallery_item.default.yml
Labels: pass code review, pass functional review, ready to merge

#268 YALB-1195: Events: Add to Calendar Link (BE)
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: pass code review, pass functional review, ready to merge

#277 YALB-1209: Allows xlsx files to be uploaded
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml
Labels: pass code review, pass functional review, ready to merge

#270 YALB-885: Metadata Enable Redirects
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/redirect_404.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/redirect_domain.domains.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.redirect_404.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/src/Config/CaptchaV2ConfigOverrides.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/src/Config/CaptchaV3ConfigOverrides.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_captcha/ys_captcha.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/src/Config/MailConfigOverrides.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_mail/ys_mail.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/src/Config/SecretsConfigOverridesBase.php
  web/sites/default/settings.php
Labels: pass code review, pass functional review, ready to merge

#281 YALB-1199: Media: Organize media on install (BE)
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/images.json
Labels: pass code review, pass functional review, ready to merge

#273 YALB1145: Levers form: Add icons and custom controls
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/icons/lever-basic-menu.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/icons/lever-mega-menu.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/icons/lever-nav-center.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/icons/lever-nav-left.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/icons/lever-nav-right.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/Form/ThemesSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemesTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge

#285 YALB-1102: Add CI jobs for releases
  web/private/scripts/confim.php
Labels: pass code review, ready to merge

#287 YALB-609: Page lists and grid display modes
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#282 YALB-340: Google Analytics
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/google_analytics.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
Labels: pass code review, pass functional review, ready to merge

#276 YALB-1198: Events: Exposed filters on dynamic list (BE)
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_category.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_category.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_category.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#290 YALB-1211: Exclude a term in views
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.taxonomy_lookup.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/ExcludeTaxonomyTerms.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: pass code review, pass functional review, ready to merge

#291 YALB-1231: Create and populate categories
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.user.user.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_event_type.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_category.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_event_type.yml
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_posts.yml
  web/profiles/custom/yalesites_profile/config/sync/migrate_plus.migration.ys_terms.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_type.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.post_category.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/config/install/migrate_plus.migration.ys_terms.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_starterkit/content/terms.json
Labels: pass code review, pass functional review, ready to merge

#293 YALB-971: LocalDev: Theme setup scripts fix
  scripts/local/local-git-checkout.sh
Labels: needs review
