Repository yalesites-org/yalesites-project, pull requests merged in 2024-03, with the labels that each got.

#596 Backport v1.1.0 changes into develop
  .ci/github/deploy_release_sites
  .github/workflows/build_deploy_and_test.yml
  .github/workflows/release.yml
  patches/layout_builder_browser/3408935-and-3409153-8.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
Labels: needs review

#598 YSP-414: Deleting used content.school_logo media results in site wide page errors
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
Labels: needs review, pass code review, pass functional review, pass a11y review

#590 YSP-374: Deleting focus header image results in sitewide error
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, pass a11y review

#610 AYH-20: Add ai_engine to platform
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#613 YSP-437: v1.2.0: Media preview link contrast issue
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: pass code review, pass functional review, pass a11y review
