Repository yalesites-org/yalesites-project, pull requests merged in 2024-10, with the labels that each got.

#774 YSP-690: Deprecation of parameters with default values order
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review

#737 YSP-593: ServiceNow Knowledge Base Syncing
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/migrations/servicenow_knowledge_base_article_block.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/migrations/servicenow_knowledge_base_articles.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/BasicAuthWithKeys.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/Controller/RunMigrations.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/Form/ServiceNowSettings.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/Plugin/migrate/process/LayoutBuilderSections.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/Plugin/migrate_plus/authentication/ServiceNowAuth.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/src/ServiceNowManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_servicenow/ys_servicenow.services.yml
Labels: needs review, pass functional review

#770 YSP-680: PRESIDENT: Add dial to image banner to allow default and large image display
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.image_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image_banner.field_media.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image_banner.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
Labels: pass functional review

#768 YSP-346: Add pronoun field
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.profile.field_pronouns.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_pronouns.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: pass functional review

#753 JAKALA: Add Calendar display option to Views Block for Events
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Controller/EventsCalendarController.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Service/EventsCalendar.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Service/EventsCalendarInterface.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-events-calendar.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.services.yml
Labels: pass functional review

#777 YSP-693: Increase hard limit on spotlights to 650 characters
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
Labels: needs review

#778 YSP-697: Image Banner not respecting focal point
  README.md
Labels: don't merge

#780 Revert "YSP-697: Image Banner not respecting focal point"
  README.md
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#772 YSP-559: Update NPM Packages on Drupal 10.3
  .github/workflows/build_deploy_and_test.yml
  .nvmrc
  composer.json
  package.json
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/ys_alert.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: needs review
