Repository yalesites-org/yalesites-project, pull requests merged in 2024-01, with the labels that each got.

#471 YALB-1588: Starterkit: Install ys_starterkit content on new sites
  .gitignore
  docs/export-starterkit-content.md
  package.json
  scripts/local/build-with-install.sh
  scripts/local/setup.sh
  scripts/local/starterkit/create-export
  scripts/shared/content-import.sh
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#492 YALB-1169 Links: Enable WYSYWIG tools for anchor links
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
Labels: pass code review, pass functional review, ready to merge

#515 YALB-959 min max referenced items
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.gallery.field_gallery_items.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.media_grid.field_media_grid_items.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.tabs.field_tabs.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/block-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review

#530 YALB-1663: User getting error page when clicking "edit layout and content" in top menu
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
Labels: needs review, pass a11y review

#526 YALB-1686: Allow rtf file uploads
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#535 rel-100-quicklink-format-fix: Re-introduce heading_html format
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_text.yml
Labels: pass functional review, ready to merge

#525 YALB-1685: Bug: Error when going to "Manage Settings" on certain pages
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#523 YALB-1368: allow links to open in a new tab
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
Labels: pass code review, pass functional review, ready to merge

#541 fix: YALB-959 - revert site admin access block library permission
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge

#522 YALB-1588: Media links redirect to files
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.anonymous.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml
Labels: pass code review, pass functional review, ready to merge

#521 YALB-1444: Allow front page link autocomplete | YALB-1387: Improve link help text
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.button_link.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.quick_links.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.callout_item.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.custom_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.button_link.field_button_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.quick_links.field_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.callout_item.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.custom_card.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.text.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.anonymous.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.authenticated.yml
Labels: pass code review, pass functional review, ready to merge

#542 rel-100-hotfix: Submenu Display Fix
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, ready to merge

#547 YALB-1696: Hotfix: Can't configure Page title as Site admin
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/block-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#543 REL-100 Hotfix: add guard clauses to bypass <nolink>
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#544 fix: YALB(1963): Hotfix: Text Style Variation not set on existing blocks
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
Labels: pass code review, pass functional review
