Repository yalesites-org/yalesites-project, pull requests merged in 2024-11, with the labels that each got.

#793 v1.10.0: Multiple fixes
  patches/layout_builder_browser/3408935-and-3409153-9.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: needs review

#794 fix(v1.10.0): bump quick node clone to 1.19.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#799 Backport v1.10.0 changes from master
  composer.json
  pantheon.yml
  patches/layout_builder_browser/3408935-and-3409153-9.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.webform_default.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.heading_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.plain_text.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.restricted_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.webform_default.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.advanced.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.all_blocks.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.basic.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.media.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.archive.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.block_content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.editoria11y_dismissals.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.editoria11y_results.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.export_media.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.export_nodes.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.export_taxonomy.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.files.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.frontpage.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.glossary.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.moderated_content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.redirect.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.redirect_404.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.section_library.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.taxonomy_lookup.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.user_admin_people.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.watchdog.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.webform_submissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
Labels: needs review

#797 IYY-267: Add Last Updated by to Content admin
  web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
Labels: pass code review, pass functional review

#808 Update drupal core to 10.3.10
  composer.json
Labels: pass code review, pass functional review, ready to merge

#805 Hotfix: Update LocalistJson function signature
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_metatags.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_metatags.yml
  web/profiles/custom/yalesites_profile/config/sync/metatag.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Plugin/migrate_plus/data_parser/LocalistJson.php
Labels: pass code review, pass functional review, ready to merge
