Repository yalesites-org/yalesites-project, pull requests merged in 2024-04, with the labels that each got.

#612 YSP-418: Fix double-encoded document links
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review

#605 YSP-302 Hide empty exposed filters
  patches/selective_better_exposed_filters/selective_better_exposed_filters-3432551.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/views.view.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.event_list.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.post_list.yml
Labels: pass code review, pass functional review, ready to merge

#615 YSP-440: v1.2.0: Focal point not present in block media add
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.media_library.yml
Labels: pass code review, pass functional review, ready to merge

#623 Backport V1.2.0 fixes back to develop
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.media_library.yml
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review

#632 YSP-292: Organize the profile edit form
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.profile.field_media.yml
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: needs review, pass code review, pass functional review

#621 YSP-430: Canvas user need to allow two call to actions in banner
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link_two.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_link_two.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_link_two.yml
Labels: pass code review, pass functional review

#620 YSP-427 - Hero Banner breadcrumb issue
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#582 YSP-143: Add description and tag fields to media
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.background_video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.background_video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.image.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.background_video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.background_video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.background_image_16_9_focus_header.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_16_5.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_profile.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.content_spotlight_portrait_2_3.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_content_width.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_float.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.profile_directory_card_1_1_.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.text_with_image_feature_equal.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.token.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_media_video_file.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_tags.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_media_file.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.document.field_tags.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.image.field_tags.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.video.field_tags.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_tags.yml
  web/profiles/custom/yalesites_profile/config/sync/media.type.video.yml
Labels: pass code review, pass functional review, ready to merge

#627 YSP-419: Rebrand Twitter to X
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.social_links.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/SocialLinksManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/instagram.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/powerbi.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/qualtrics.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/soundcloud.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/twitter.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/x-twitter.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/Twitter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: pass code review, pass functional review, ready to merge

#635 YSP-478: Bug: Adding Profile Content Block to Post/Events results in error
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
Labels: pass code review, pass functional review, ready to merge

#630 YSP-399: Localist: Embedding widgets
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/localist.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/Localist.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: needs review, pass code review, pass functional review

#639 chore(fix-phpcs): auto-fix new phpcs analyzer findings
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Form/AlertSettings.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/src/Plugin/Block/AlertBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesFooterBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/YaleSitesMediaManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceBase.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldFormatter/EmbedDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/Field/FieldWidget/EmbedDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/media/Source/Embed.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/src/ToolbarItemsService.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicPreviewFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: needs review, pass code review, pass functional review
