Repository yalesites-org/yalesites-project, pull requests merged in 2024-02, with the labels that each got.

#556 Backport: master hotfixes into develop
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/block-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review

#467 YALB-520: Links: Dynamically apply link treatments
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSourceManager.php
Labels: needs review, pass code review, pass functional review, ready to merge, pass a11y review

#558 YALB-1568: FE Bug: Profile page breadcrumb issue
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review, pass code review, pass functional review

#559 YALB-1703: Bug: Updating site settings changes home page path from page node path to URL alias
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: pass code review, pass functional review, ready to merge

#524 YALB-1681 - Support light and dark admin themes
  web/profiles/custom/yalesites_profile/config/sync/ys_admin_theme.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_alert/css/ys_alert.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/header-footer-settings.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_toolbar/css/ys_toolbar.theme.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/css/views-basic.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css
  web/themes/custom/ys_admin_theme/css/gin-color-overrides.css.map
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-color-overrides.scss
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
  web/themes/custom/ys_admin_theme/ys_admin_theme.libraries.yml
Labels: needs review, pass code review

#568 YSP-324: Deprecation warning in smart_date causes axe to find issue
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#552 YALB-680: External source for content in lists
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_external_source.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_external_source.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_external_source.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.profile.field_external_source.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_external_source.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/EventSubscriber/ExternalSourceRedirectSubscriber.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
Labels: needs review, pass code review, pass functional review, ready to merge

#581 YSP-355: External view results don't have external icon
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileContactBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
Labels: pass code review, pass functional review, ready to merge

#560 YALB-1691: Bug: Min/max referenced items in reusable block
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/block-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review

#587 YSP-371: Reusable Blocks created via backend not available in Block Picker
  patches/layout_builder_browser/3408935-and-3409153-8.patch
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
Labels: needs review, pass code review, pass functional review

#588 YSP-373: Front page not updated to node reference
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
Labels: needs review, pass code review, pass functional review

#589 YSP-318: Can't clone a profile
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge
