Repository yalesites-org/yalesites-project, pull requests merged in 2024-06, with the labels that each got.

#671 YSP-299 - Update "term" description in Views block]
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: pass code review, pass functional review, ready to merge

#667 YSP-532: Increase grand hero video size maximum
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.background_video.field_media_video_file.yml
Labels: pass code review, pass functional review

#674 YSP-560: Localist: Update Event lists + default image updates
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: needs review, pass code review, pass functional review

#656 YSP-518 - Tech debt remove uninstalled modules
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/src/SecretsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/ys_secrets.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_secrets/ys_secrets.services.yml
Labels: needs review

#665 YSP-431 Wire/Add/Tweak Call-to-Action button utility nav
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js
Labels: pass code review, pass functional review, ready to merge

#670 YSP-494 - Allow content spotlight as a banner
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
Labels: pass code review, pass functional review, ready to merge

#676 YSP-487: Add JWPlayer Embed
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/jwplayer.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/JWPlayer.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: needs review

#655 YSP-509: Add Code Style to WYSIWYGttons to basic editor
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
Labels: pass code review, pass functional review, ready to merge

#662 YSP-541: Embed: Add Microsoft Forms
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/msforms.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/MicrosoftForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#673 YSP-548 Views: Offset results
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review
