Repository yalesites-org/yalesites-project, pull requests merged in 2024-09, with the labels that each got.

#750 Hotfix: YSP-649: EDT vs EST from Localist causing incorrect time render [skip ci]
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
Labels: needs review

#749 Hotfix: YSP-632: AI: AI modules disabled on release
  web/profiles/custom/yalesites_profile/config/sync/ai_engine_chat.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/ai_engine_metadata.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: needs review

#734 YSP-631: GaAccount::__construct(): Argument #1 ($account) must be of type string, null given
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review, pass code review, pass functional review

#745 JAKALA: Color Palette for ONHA
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review, pass a11y review

#736 JAKALA: Secondary Link for Spotlight blocks
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_link_two.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_link_two.yml
Labels: needs review, pass code review, pass functional review

#727 JAKALA: Add Content Type filter to Search Page
  web/profiles/custom/yalesites_profile/config/sync/search_api.index.node_index.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.search.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/CoreTwigExtension.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/ViewsSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesSearchFormBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/templates/ys-search-form.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
Labels: needs review

#748 YSP-641: Image banner block
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.image_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.image_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.image_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.image_banner.field_media.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.image_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/image-banner.svg
Labels: pass functional review, pass a11y review

#751 YSP-662: PRESIDENT: allow center or larger view of video block
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.video.field_style_alignment.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
Labels: pass functional review, pass a11y review

#752 YSP-647: PRESIDENT: Ability to bulk Unpublish
  web/profiles/custom/yalesites_profile/config/sync/system.action.publish_moderated_content.yml
  web/profiles/custom/yalesites_profile/config/sync/system.action.unpublish_moderated_content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedPublish.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedUnpublish.php
Labels: needs review, pass functional review

#742 JAKALA: Views block enhancements
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.paragraph.cta_link.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.page_category.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.view.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_link.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.paragraph.cta_link.preview.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.taxonomy_term.page_category.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_heading_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.view.field_view_params.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_category.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.paragraph.cta_link.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_heading_links.yml
  web/profiles/custom/yalesites_profile/config/sync/paragraphs.paragraphs_type.cta_link.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.page_category.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldFormatter/ViewsBasicDefaultFormatter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/PostYearFilter.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/templates/views-basic-formatter-default.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: pass code review, pass functional review, pass a11y review

#755 YSP-652: Views setting Can or Must selection is not selected on configure
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, pass a11y review

#738 JAKALA: Theme Dial for Grand Hero
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: pass code review, pass functional review, pass a11y review

#756 YSP-671: Unable to Select Media for blocks with images by filtering
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, pass a11y review

#761 fix(views-text): Change any/all text to not include category
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: pass code review, pass functional review

#764 Hotfix v1.8.0: Default show_thumbnail to true for existing views
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: needs review, pass functional review

#769 Fix linting issues on develop preventing multidev creation
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedPublish.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Action/ModeratedUnpublish.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Service/LayoutUpdater.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Plugin/migrate_plus/data_parser/LocalistJson.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/filter/PostYearFilter.php
Labels: needs review
