Repository yalesites-org/yalesites-project, pull requests merged in 2024-07, with the labels that each got.

#697 YSP-588: Pagination after first page doesn't comply with ascending/descending dates for events
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
Labels: needs review

#680 YSP-335: New block: In-Line Message
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.inline_message.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.inline_message.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.inline_message.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.inline_message.field_heading.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.inline_message.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.inline_message.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.inline_message.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.inline_message.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/in-line-message.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: needs review, pass code review, pass functional review, ready to merge

#692 YSP-570: Views: Change limit help text
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/assets/js/views-basic.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
Labels: needs review, pass functional review, ready to merge

#693 YSP-576: Enable new block permissions
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: needs review

#706 YSP-613: Bump ai_engine in YaleSites to 1.2.3
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review, pass code review, ready to merge

#704 YSP-611: Localist: Views errors after localist enable
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
Labels: pass code review, pass functional review, ready to merge

#701 YSP-551: Toggling a block as reusable on a page leads to white screen error page
  patches/layout_builder/1330eff91b1234979cf697a66a48e34eb116b441-1.patch
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review, pass code review, pass functional review
