Repository yalesites-org/yalesites-project, pull requests merged in 2024-05, with the labels that each got.

#637 YSP-458: Editorial Workflow: Display improvements to right panel
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/EventSubscriber/AlterModerationSidebarController.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: needs review, pass code review, pass functional review

#650 YSP-529: V1.3.0: remove the configure button on moderation placeholder in /layout
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
Labels: needs review

#652 YSP-529/530 - Layout builder fixes
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
Labels: needs review

#647 fix(YSP-525): v1.3.0: Bug: Bulk publish/unpublish operations do nothing
  web/profiles/custom/yalesites_profile/config/sync/views.view.content.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_events.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_pages.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_posts.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.manage_profiles.yml
Labels: pass code review, pass functional review, ready to merge

#648 fix(YSP-526): V1.3.0: Reference Card Label Change
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_content_ref.yml
Labels: pass code review, pass functional review, ready to merge

#649 fix(YSP-528): V1.3.0: Media Library add tag column in view
  web/profiles/custom/yalesites_profile/config/sync/views.view.media.yml
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#653 YSP-517: Tech debt consistent field settings
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.content_spotlight_portrait.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.reference_card.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_style_color.yml
Labels: pass code review, pass functional review, ready to merge

#658 YSP-521 - AX: Hide Revert button on layout builder
  web/profiles/custom/yalesites_profile/config/sync/gin_lb.settings.yml
Labels: pass code review, pass functional review, ready to merge

#664 YSP-479 Wrong alignment for Reusable Blocks in Posts, Profiles and Events
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
Labels: needs review, pass code review, pass functional review, ready to merge

#663 YSP-540 give permissions to platform admins to assign roles
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
Labels: needs review, pass code review, pass functional review

#642 Ysp 321 profile vertical images
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Form/YaleSitesLayoutsSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/ProfileMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Service/LayoutUpdater.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Service/LayoutUpdaterLegacy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-profile-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.deploy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.services.yml
Labels: needs review, pass code review, pass functional review

#654 YSP-538: Provide a menu link error on Publish
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
Labels: pass code review, pass functional review, ready to merge
