Repository yalesites-org/yalesites-project, pull requests merged in 2025-01, with the labels that each got.

#809 YSP-293: Log out of CAS when logging out of drupal
  web/profiles/custom/yalesites_profile/config/sync/cas.settings.yml
Labels: needs review, pass code review, pass functional review

#843 Hotfix: YSP-791: Bump quick node clone to 1.20.0
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PageMetaBlock.php
Labels: needs review

#844 V1.12.1 Backport
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PageMetaBlock.php
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
Labels: needs review

#836 IYY-299: Show help text about Locks to only those that can lock things
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.wrapped_text_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.wrapped_text_callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.wrapped_text_callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_text_callout.field_callout_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_text_callout.field_style_color.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_text_callout.field_style_position.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.wrapped_text_callout.field_text.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_callout_text.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.button_link.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.callout.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.content_spotlight.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.content_spotlight_portrait_.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.divider.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.link_grid.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.profile_contact_info.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quick_links.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quote.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quote_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.reference_card.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.text.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.video.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.wrapped_image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.wrapped_text_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/wrapped-callout.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: needs review, pass code review, pass functional review

#838 IYY-302: Add vertical text alignment to Spotlights
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_alignment.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_style_alignment.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.component_overrides.yml
Labels: needs review, pass code review, pass functional review

#807 IYY:297: Create new "Coral" Theme
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review, ready to merge

#826 IYY-283: Site editors can create a ½ - ½ layout and ⅓ - ⅓ - ⅓ layout
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/banner/layout--banner.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/page-meta/layout--page-meta.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/three_column_33_33_33/layout--three-column--33-33-33.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/three_column_33_33_33/three-column_33_33_33.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/two_column_50_50/layout--two-column--50-50.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/two_column_50_50/two-column_50_50.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Layout/YSLayoutBanner.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Layout/YSLayoutOptions.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.layouts.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css
Labels: pass code review, pass functional review, ready to merge

#839 IYY-289: Utility Navigation Dropdown Menu Link Button
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/core.menu.static_menu_link_overrides.yml
  web/profiles/custom/yalesites_profile/config/sync/menu_item_limit.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/system.menu.utility-drop-button-navigation.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/util-nav-dropdown.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/FooterSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SettingsFormTrait.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesTitleBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
Labels: pass code review, pass functional review, ready to merge

#834 IYY-287: Install and enable Drupal Book module
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_custombooknavigation.yml
  web/profiles/custom/yalesites_profile/config/sync/book.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_mode.node.print.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/js/book.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/Controller/YSBookController.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/page-meta/layout--page-meta.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/config/install/ys_themes.theme_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/levers.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/js/levers.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: needs review
