Repository yalesites-org/yalesites-project, pull requests merged in 2025-08, with the labels that each got.

#1009 Hotfix: IYY-360: Show CAS'd content in Content Collection Menu
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/Controller/YsBookController.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/YsBookServiceProvider.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/YsExpandBookManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/src/Menu/YsNodeAccessLinkTreeManipulator.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.module
Labels: pass code review, pass functional review, ready to merge

#1039 Hotfix: YSP-1087: Environment Indicator Changes
  README.md
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/ys_themes.module
  web/sites/default/settings.php
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: ready to merge

#1052 Update atomic to 1.57.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#1054 Hotfix: Sort tree siblings by weight and title
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/src/YsExpandBookManager.php
Labels: pass code review, pass functional review, ready to merge

#1057 YSP-860: Cache not cleared when updating external link in Post
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/EventSubscriber/ExternalSourceRedirectSubscriber.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
Labels: pass code review, pass functional review, ready to merge
