Repository yalesites-org/yalesites-project, pull requests merged in 2025-03, with the labels that each got.

#889 IYY-328: Chatbot is floating in bottom right of page
  README.md
  web/profiles/custom/yalesites_profile/composer.json
Labels: ready to merge

#894 IYY-335: Follow-ups on Book Module/Secondary Nav
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.single.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_dynamic_book_nav.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_dynamic_book_nav.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css
Labels: needs review, needs work

#916 IYY-346 :: CKeditor basic - enable advanced link options
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
Labels: pass code review, pass functional review

#859 IYY-323: PO Boxes Filtering Embed Widget - Drupal
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/github.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/GitHubApplet.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: pass code review, pass functional review, ready to merge

#910 IYY-351: Content Collection Bugs
  README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review

#920 Bump atomic to 1.21.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: ready to merge
