Repository yalesites-org/yalesites-project, pull requests merged in 2025-09, with the labels that each got.

#1048 YSP-1039: Embed: Google Calendar
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/GoogleCalendar.php
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#1062 AX: Required asterisks color contrast in dark mode fails
  web/themes/custom/ys_admin_theme/css/gin-custom.css
  web/themes/custom/ys_admin_theme/css/gin-custom.css.map
  web/themes/custom/ys_admin_theme/scss/gin-custom.scss
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#1050 YSP-1094 :: Fix Taxonomy Manager access
  web/profiles/custom/yalesites_profile/modules/custom/ys_taxonomy_manager/ys_taxonomy_manager.routing.yml
Labels: pass code review, pass functional review, ready to merge

#1059 YSP-981 :: Footer: Add Bluesky Icon Option to Social Links
  web/profiles/custom/yalesites_profile/config/sync/addtoany.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/SocialLinksManager.php
Labels: pass code review, pass functional review, ready to merge

#1067 Event Teaser Image: Allow portait images
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
Labels: needs review, pass code review, pass functional review

#1055 Add Redis support
  pantheon.upstream.yml
  web/profiles/custom/yalesites_profile/composer.json
  web/sites/default/settings.php
  web/sites/default/settings.redis.php
Labels: needs review

#1079 Backport ys_ai fix to develop branch
  web/profiles/custom/yalesites_profile/modules/custom/ys_ai/ys_ai.info.yml
Labels: pass code review, pass functional review, ready to merge

#1083 RC: Make resource media field required
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.resource.field_media.yml
Labels: pass functional review, ready to merge

#1091 Bump Atomic to 1.62.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: ready to merge

#1093 Update atomic to 1.63.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: ready to merge
