Repository yalesites-org/yalesites-project, pull requests merged in 2025-05, with the labels that each got.

#965 YSP-899: PostMetaBlock throwing first() error with field_authors
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: needs review, pass functional review

#966 YSP-893: Bump AI Engine to v1.2.10
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass code review, pass functional review, ready to merge

#971 YSP-912: Change default for social media sharing on Post content type
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_show_teaser_lead_in.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_show_social_media_sharing.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_show_social_media_sharing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-post-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: pass code review, pass functional review, ready to merge

#972 YSP-927: Show Content Type in LinkIt module
  web/profiles/custom/yalesites_profile/config/sync/linkit.linkit_profile.default.yml
Labels: pass code review, pass functional review, ready to merge

#943 IYY-342: All Yale Results powered by Google Programmable Search
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/gcse.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/gcse.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
Labels: pass code review, pass functional review, ready to merge

#974 Update atomic to 1.47.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#975 Add permissions for wrapped_text_callout content
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
Labels: pass code review, pass functional review, ready to merge

#976 Backport v1240
  README.md
Labels: needs review

#980 Hotfix: YSP-943/YSP-945: Grand Hero and Table fixes
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/README.md
Labels: pass code review, pass functional review, ready to merge
