Repository yalesites-org/yalesites-project, pull requests merged in 2025-04, with the labels that each got.

#905 YSP-824 Admin Label automatically is the block name
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#922 YSP-716 :: Add "Contained Narrow" Design Option to Grand Hero Block
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
Labels: pass code review, pass functional review, ready to merge

#908 YSP-844: Event Meta Block Date Visibility Improvements
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/pager/ViewsBasicFullPager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/style/ViewsBasicDynamicStyle.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: needs review

#917 YSP-840: Add Event Integration Sync Button for All Users (module)
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_integrations.integration_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Controller/RunMigrations.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Plugin/ys_integrations/CampusGroupsIntegrationPlugin.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/Attribute/Integration.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/Controller/YsIntegrationsController.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/Form/YsIntegrationSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/IntegrationPluginBase.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/IntegrationPluginInterface.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/src/IntegrationPluginManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/templates/ys-integrations-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_integrations/ys_integrations.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Controller/RunMigrations.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/Plugin/ys_integrations/LocalistIntegrationPlugin.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.routing.yml
Labels: pass functional review, ready to merge

#926 YSP-370: Add Offset/Inline Design Options to Landscape Spotlight Block
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_focus.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_style_variation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_focus.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
Labels: pass functional review, ready to merge

#914 IYY-353: Variables showing on the Posts for read time and teaser lead in
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
Labels: pass functional review, ready to merge

#898 YSP-761 :: Add available blocks to regions for new layouts
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
Labels: needs review, pass code review, pass functional review

#928 Update atomic to 1.45.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#939 YSP-493 :: Remove Text Centering and Left Justified Options from Text Block WYSIWYG Editor
  web/profiles/custom/yalesites_profile/config/sync/editor.editor.basic_html.yml
  web/profiles/custom/yalesites_profile/config/sync/filter.format.basic_html.yml
Labels: pass code review, pass functional review, ready to merge, pass a11y review

#942 YSP-858 :: Taxonomy sub item filter shows multiple instances
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
Labels: pass code review, pass functional review, ready to merge

#934 YSP-589: Add Page Content Type Support to Reference Card Block
  web/profiles/custom/yalesites_profile/config/sync/block_content.type.reference_card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.single.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_content_ref.yml
Labels: pass code review, pass functional review, ready to merge

#946 YSP-874: Quote Block 'Bar Right' Style Alignment Issues in Narrow Sections
  README.md
Labels: don't merge, pass code review, pass functional review

#931 YSP-367: Add support for .webp
  web/profiles/custom/yalesites_profile/config/sync/field.field.media.image.field_media_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.media.field_media_image.yml
Labels: pass code review, pass functional review, ready to merge

#936 YSP-880: Change default site email from noreply@yale.edu to noreply@noreply.yale.edu
  web/profiles/custom/yalesites_profile/config/sync/system.site.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.install
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#890 Update to drupal/core:10.3.14
  composer.json
  web/profiles/custom/yalesites_profile/composer.json
Labels: pass functional review, ready to merge

#935 YSP-333: Rearrange block picker + add a column to the picker (3 -> 4)
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.accordion.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.action_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.button_link.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.calendar_list.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.callout.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.content_spotlight.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.content_spotlight_portrait_.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.custom_cards.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.divider.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.embed.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.facts.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.gallery.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.grand_hero.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.image_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.inline_message.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.link_grid.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.media_grid.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.media_image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.media_video.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.postfeed.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.profile_contact_info.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.profile_directory.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quick_links.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quote.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.quote_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.reference_card.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.tabs.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.taxonomy_display.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.text.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.tiles.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.video.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.video_banner.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.view.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.webform.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.wrapped_image.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.wrapped_text_callout.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.advanced.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.basic.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.calls_to_action.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.dynamic_content.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.featured_content.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.media.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_blockcat.text_and_content.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/css/layout-builder-browser.css
Labels: pass code review, pass functional review, ready to merge

#945 Fix CAS login under Lando
  web/sites/ys.settings.local.php
Labels: pass code review, pass functional review, ready to merge

#937 YSP-803: Reduce Excessive Padding Between Breadcrumbs and Banner Blocks
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/page-meta/layout--page-meta.html.twig
Labels: pass code review, pass functional review, ready to merge

#911 IYY-343 :: Views tool: Allow to filter taxonomy on the new custom vocab
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#837 YSP-683: ONHA program and news migration
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/config/optional/migrate_plus.migration.ys_onha_news.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/config/optional/migrate_plus.migration.ys_onha_news_terms.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/config/optional/migrate_plus.migration.ys_onha_program_body.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/config/optional/migrate_plus.migration.ys_onha_programs.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/config/optional/migrate_plus.migration_group.ys_onha.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/src/Plugin/migrate/process/onha/BodyToLayoutBuilder.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_migrate/ys_migrate.info.yml
Labels: needs review

#951 Update Atomic to v1.46.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#953 YSP-891/YSP-876: Revert dynamic content collections/Home landing page removal
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.page.field_dynamic_book_nav.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_dynamic_book_nav.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_book/ys_book.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Block/YaleSitesBreadcrumbBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/src/ThemeSettingsManager.php
Labels: pass code review, pass functional review, ready to merge

#938 YSP-863 :: Add Section Padding Options
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/three_column_33_33_33/layout--three-column--33-33-33.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/two_column/layout--two-column.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/two_column_50_50/layout--two-column--50-50.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: pass code review, pass functional review, ready to merge

#956 YSP-892: Design treatment for active Content Collection parent menu items and location move
  README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/layouts/page-meta/layout--page-meta.html.twig
Labels: pass code review, pass functional review, ready to merge

#907 LIB: Overlay PNG
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.grand_hero.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_overlay_png.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.grand_hero.field_replace_heading_with_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_overlay_png.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_replace_heading_with_image.yml
  web/profiles/custom/yalesites_profile/config/sync/image.style.grand_hero_overlay_image.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/field.field.block_content.grand_hero.field_display_mode.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/field.storage.block_content.field_display_mode.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/js/grand-hero-form.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge
