Repository yalesites-org/yalesites-project, pull requests merged in 2025-07, with the labels that each got.

#1002 YSP-543 :: Add Coffee Module to YaleSites Platform
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/coffee.configuration.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/.!54886!ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.coffee.inc
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review

#1005 YSP-885 :: Add Environment Indicator Module
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/environment_indicator.indicator.yml
  web/profiles/custom/yalesites_profile/config/sync/environment_indicator.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.contributor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.editor.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/sites/default/settings.php
  web/themes/custom/ys_admin_theme/css/gin-custom.css
Labels: needs review

#1008 YSP-948 :: Add Caption Field to Spotlight Blocks (Landscape and Portrait)
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight.field_caption.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.content_spotlight_portrait.field_caption.yml
Labels: pass code review, pass functional review, ready to merge

#1010 YSP-938: Reference card page CAS protected not showing
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_content_ref.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/EntityReferenceSelection/CasAwareSelection.php
Labels: pass code review, pass functional review, ready to merge

#997 YSP-904: YPS: Add Image Background to Action Banner and Callout Blocks
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.callout.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.cta_banner.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.callout.field_overlay_background_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_link.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.cta_banner.field_overlay_background_image.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_overlay_background_image.yml
Labels: pass code review, pass functional review, ready to merge

#1020 Update atomic to 1.51.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#1028 YSP-1072: Admin label change to stop overriding on 'configure'
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass code review, pass functional review, ready to merge

#1006 YSP-920 :: Clean Up User Addition Experience for Non-Platform Admins
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.action.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: pass functional review, ready to merge

#1003 YSP-986: Allow to force CAS login site wide
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/EventSubscriber/CasUser1BypassSubscriber.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/SiteSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.services.yml
Labels: needs review

#1034 Bump atomic to 1.52.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#1037 Bump atomic to 1.53.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: ready to merge

#1038 Accessibility RC fixes
  web/profiles/custom/yalesites_profile/composer.json
  web/themes/custom/ys_admin_theme/css/admin-ui.css
  web/themes/custom/ys_admin_theme/css/admin-ui.css.map
  web/themes/custom/ys_admin_theme/scss/admin-ui.scss
Labels: needs review, pass code review, pass functional review
