Repository yalesites-org/yalesites-project, pull requests merged in 2025-02, with the labels that each got.

#849 IYY-271/IYY-300: Views Tool Changes
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.services.yml
Labels: needs review, pass code review, pass functional review

#866 YSP-730: Revert changes made in #669
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
Labels: needs review

#840 YSP-770: Campus Groups Integration
  web/profiles/custom/yalesites_profile/config/sync/config_ignore.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_event_id.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.event.field_event_source.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_event_id.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_event_source.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.event_sources.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.platform_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/README.md
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_taxonomy.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/CampusGroupsConfig.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/CampusGroupsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Controller/RunMigrations.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Form/CampusGroupsSettings.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Plugin/migrate/source/CampusGroupUrl.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.permissions.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.services.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.routing.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/migrations/localist_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/migrations/localist_source_taxonomy.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/LocalistManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
Labels: pass functional review

#869 IYY-271: HOTFIX Fixes ambiguous nid error on some views
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review

#857 YSP-760: Editing an image popup doesn't show save button
  web/profiles/custom/yalesites_profile/modules/custom/ys_themes/css/ys-themes.css
Labels: pass functional review, ready to merge

#860 YSP-769: Add "Pin to Top" visual indicator
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: needs review, pass functional review

#862 YSP-765 Taxonomy display block (Backend)
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/layout_builder_browser.layout_builder_browser_block.taxonomy_display.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/images/preview-icons/taxonomy-display.svg
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/TaxonomyDisplayBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-taxonomy-display-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: pass code review, pass functional review, ready to merge

#854 IYY-280: Visitors can share Posts
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/addtoany.settings.yml
  web/profiles/custom/yalesites_profile/config/sync/block.block.atomic_addtoanysharebuttons.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.background_video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.background_video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.document.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.embed.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.embed.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.background_image_16_9_focus_header.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_16_5.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.banner_profile.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_list_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.card_secondary_3_2.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.content_spotlight_portrait_2_3.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_content_width.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.image_float.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.profile_directory_card_1_1_.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.text_with_image_feature_equal.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.image.token.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.media.video.media_library.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.directory.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/core.extension.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_hide_sharing_links.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_hide_sharing_links.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/PostMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-post-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
Labels: pass code review, pass functional review, ready to merge

#874 Update atomic to 1.40.0
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review

#880 YSP-678 Multiple views exposed filters on a page only work on last instance
  web/profiles/custom/yalesites_profile/composer.json
Labels: needs review, pass code review, pass functional review, ready to merge

#877 V1.13.0 Feedback/Bug Fixes
  CODEOWNERS
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Menu/CustomTaxonomyMenuLink.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/TaxonomyDisplayBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
Labels: pass code review, pass functional review, ready to merge

#867 IYY-290: Show CAS'd content in Menu Links
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.menu_link_content.utility-navigation.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.menu_link_content.utility-navigation.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.menu_link_content.utility-navigation.field_placeholder.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.menu_link_content.field_placeholder.yml
  web/profiles/custom/yalesites_profile/config/sync/menu_item_limit.settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/config/install/ys_core.header_settings.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Form/HeaderSettingsForm.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/src/Menu/YsNodeAccessLinkTreeManipulator.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.info.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_node_access/ys_node_access.services.yml
Labels: needs review

#882 Update README.md
  README.md
Labels: ready to merge

#883 v1.13.0 Feedback Fixes 2
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.custom_vocab.default.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.custom_vocab.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
Labels: pass code review, pass functional review, ready to merge

#884 v1.13.x Feedback Fixes 3
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml
Labels: needs review

#887 V1.13.0 Backport
  .github/workflows/release_pr.yml
  README.md
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.content_spotlight_portrait.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.taxonomy_term.custom_vocab.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.event.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.profile.default.yml
  web/profiles/custom/yalesites_profile/config/sync/taxonomy.vocabulary.custom_vocab.yml
  web/profiles/custom/yalesites_profile/config/sync/user.role.site_admin.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold.yml
  web/profiles/custom/yalesites_profile/config/sync/views.view.views_basic_scaffold_events.yml
  web/profiles/custom/yalesites_profile/config/sync/ys_themes.component_overrides.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/src/Plugin/Menu/CustomTaxonomyMenuLink.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.deploy.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.links.menu.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/TaxonomyDisplayBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/views/sort/ViewsBasicSort.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/yalesites_profile.info.yml
Labels: ready to merge

#827 LIB: LibCal Embed
  README.md
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.page.default.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/css/LibCal.css
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/js/LibCal.js
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/LibCal.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.libraries.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.module
Labels: needs review, pass code review, pass functional review, ready to merge

#895 revert: release action can only run on push event, not pull_request
  .github/workflows/release.yml
  package.json
Labels: pass code review

#891 YSP-829: Hotfix: v1.13.0: Campus Groups API key support
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/migrations/campus_groups_events.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Form/CampusGroupsSettings.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/src/Plugin/migrate/source/CampusGroupUrl.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.info.yml
Labels: needs review, pass code review, pass functional review

#888 YSP-826: Hotfix: clear render cache for view items
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.services.yml
Labels: needs review, pass functional review, ready to merge

#896 Hotfix: v1.13.0: Add LibCal embed logo
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/images/icons/springshare-libcal.png
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/src/Plugin/EmbedSource/LibCal.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_embed/ys_embed.install
Labels: pass functional review, ready to merge

#868 IYY-303: Callout component animations and background image options
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.tiles.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.tiles.default.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.tiles.field_enable_animation.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_enable_animation.yml
Labels: needs review

#897 Hotfix: v1130: Remove pass by reference on $display_id
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: pass code review, pass functional review, ready to merge

#858 IYY-321: Posts can have an tagline (eyebrow)
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.block_content.reference_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_form_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.block_content.reference_card.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.card.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.condensed.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.default.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.list_item.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.search_result.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.single.yml
  web/profiles/custom/yalesites_profile/config/sync/core.entity_view_display.node.post.teaser.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.block_content.reference_card.field_show_teaser_lead_in.yml
  web/profiles/custom/yalesites_profile/config/sync/field.field.node.post.field_teaser_lead_in.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.block_content.field_show_teaser_lead_in.yml
  web/profiles/custom/yalesites_profile/config/sync/field.storage.node.field_teaser_lead_in.yml
  web/profiles/custom/yalesites_profile/modules/custom/ys_core/ys_core.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/Plugin/Field/FieldWidget/ViewsBasicDefaultWidget.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/src/ViewsBasicManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_views_basic/ys_views_basic.module
Labels: ready to merge

#901 Hotfix: v1.13.0: Campus groups add to calendar fix
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
Labels: needs review, pass functional review

#900 Hotfix: v1.13.0: Update cron to use service manager
  web/profiles/custom/yalesites_profile/composer.json
  web/profiles/custom/yalesites_profile/modules/custom/ys_campus_groups/ys_campus_groups.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/src/Plugin/Block/EventMetaBlock.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/templates/ys-event-meta-block.html.twig
  web/profiles/custom/yalesites_profile/modules/custom/ys_layouts/ys_layouts.module
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/src/MetaFieldsManager.php
  web/profiles/custom/yalesites_profile/modules/custom/ys_localist/ys_localist.module
Labels: needs review
